"""
This is for payload data and configuration.
"""
# configure the IOXApp external IP and port.
FOG_APP_IP = '0.0.0.0:8000'

# To change payload of sensor data in same format.
PAYLOAD = [[{'sensor_type': 'positionalsensor',
             'sensor_status': 'ON',
             'sensor_serial_num': 'PS100-10001'},
            {'sensor_type': 'positionalsensor',
             'sensor_status':'OFF',
             'sensor_serial_num': 'PS100-10002'},
            {'sensor_type': 'positionalsensor',
             'sensor_status':'OFF',
             'sensor_serial_num': 'PS100-10003'},
            {'sensor_type': 'positionalsensor',
             'sensor_status':'OFF',
             'sensor_serial_num': 'PS100-10004'},
            {'sensor_type': 'positionalsensor',
             'sensor_status':'OFF',
             'sensor_serial_num': 'PS100-10005'}],
           [{'sensor_type': 'positionalsensor',
             'sensor_status': 'OFF',
             'sensor_serial_num': 'PS100-10001'},
            {'sensor_type': 'positionalsensor',
             'sensor_status':'ON',
             'sensor_serial_num': 'PS100-10002'},
            {'sensor_type': 'positionalsensor',
             'sensor_status':'OFF',
             'sensor_serial_num': 'PS100-10003'},
            {'sensor_type': 'positionalsensor',
             'sensor_status':'OFF',
             'sensor_serial_num': 'PS100-10004'},
            {'sensor_type': 'positionalsensor',
             'sensor_status':'OFF',
             'sensor_serial_num': 'PS100-10005'}],
           [{'sensor_type': 'positionalsensor',
             'sensor_status': 'OFF',
             'sensor_serial_num': 'PS100-10001'},
            {'sensor_type': 'positionalsensor',
             'sensor_status':'OFF',
             'sensor_serial_num': 'PS100-10002'},
            {'sensor_type': 'positionalsensor',
             'sensor_status':'ON',
             'sensor_serial_num': 'PS100-10003'},
            {'sensor_type': 'positionalsensor',
             'sensor_status':'OFF',
             'sensor_serial_num': 'PS100-10004'},
            {'sensor_type': 'positionalsensor',
             'sensor_status':'OFF',
             'sensor_serial_num': 'PS100-10005'}],
           [{'sensor_type': 'positionalsensor',
             'sensor_status': 'OFF',
             'sensor_serial_num': 'PS100-10001'},
            {'sensor_type': 'positionalsensor',
             'sensor_status':'OFF',
             'sensor_serial_num': 'PS100-10002'},
            {'sensor_type': 'positionalsensor',
             'sensor_status':'OFF',
             'sensor_serial_num': 'PS100-10003'},
            {'sensor_type': 'positionalsensor',
             'sensor_status':'ON',
             'sensor_serial_num': 'PS100-10004'},
            {'sensor_type': 'positionalsensor',
             'sensor_status':'OFF',
             'sensor_serial_num': 'PS100-10005'}],
           [{'sensor_type': 'positionalsensor',
             'sensor_status': 'OFF',
             'sensor_serial_num': 'PS100-10001'},
            {'sensor_type': 'positionalsensor',
             'sensor_status':'OFF',
             'sensor_serial_num': 'PS100-10002'},
            {'sensor_type': 'positionalsensor',
             'sensor_status':'OFF',
             'sensor_serial_num': 'PS100-10003'},
            {'sensor_type': 'positionalsensor',
             'sensor_status':'OFF',
             'sensor_serial_num': 'PS100-10004'},
            {'sensor_type': 'positionalsensor',
             'sensor_status':'ON',
             'sensor_serial_num': 'PS100-10005'}],
           [{'sensor_type': 'positionalsensor',
             'sensor_status': 'ON',
             'sensor_serial_num': 'PS100-10001'},
            {'sensor_type': 'positionalsensor',
             'sensor_status':'ON',
             'sensor_serial_num': 'PS100-10002'},
            {'sensor_type': 'positionalsensor',
             'sensor_status':'ON',
             'sensor_serial_num': 'PS100-10003'},
            {'sensor_type': 'positionalsensor',
             'sensor_status':'ON',
             'sensor_serial_num': 'PS100-10004'},
            {'sensor_type': 'positionalsensor',
             'sensor_status':'ON',
             'sensor_serial_num': 'PS100-10005'}]
          ]
